<h1>RedCom League By-Laws</h1><p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>Number of teams</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">12</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>Divisions&nbsp;</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">3 (Random assignment)</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">After each season, the divisions will be recast randomly</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>Fee:&nbsp; &nbsp; &nbsp;</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">50$ per Season/Team</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Seasons 2022 and 2023 (i.e. 100 $) to be paid upfront before Startup Draft&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">League fees will be managed through Leaguesafe</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Future Draft Picks can be traded only in case that Participation fee for that season has been paid in full.</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><s><span style="color: rgb(192, 0, 0);">Late payment for 2024 will cause Rookie Picks to be removed from the involved manager (more details will follow)</span></s></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style="color: rgb(83, 129, 53);">New rule applicable from 2023-03-25 onwards:</span></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style="color: rgb(83, 129, 53);">League fees must be paid 1 year in advance. Deadline: 1 day prior to the official NFL rookie draft&nbsp;</span></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style="color: rgb(83, 129, 53);">Example 1) in order to have no penalty rookie picks removed, league fee 2025 must be paid until approx. end April 2024</span></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style="color: rgb(83, 129, 53);">Example 2) in order to have no penalty rookie picks removed, league fee 2026 must be paid until approx. end April 2025&nbsp;</span></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style="color: rgb(83, 129, 53);">and so on&hellip;</span></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style="color: rgb(83, 129, 53);">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style="color: rgb(83, 129, 53);">In case of delayed payments, the following penalty will be applied</span></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style="color: rgb(83, 129, 53);">Up to 1 week delay = no 1<sup>st</sup> round draft pick in the corresponding draft year (i.e. 2025 in example 1, 2026 in example 2)</span></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style="color: rgb(83, 129, 53);">Up to 2 weeks delay = no 1<sup>st</sup> + 2<sup>nd</sup> round draft pick</span></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style="color: rgb(83, 129, 53);">Up to 3 weeks delay = no 1<sup>st</sup> + 2<sup>nd</sup> + 3<sup>rd</sup> round draft pick</span></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style="color: rgb(83, 129, 53);">Up to 4 weeks delay = no 1<sup>st</sup> + 2<sup>nd</sup> + 3<sup>rd&nbsp;&nbsp;</sup>+&nbsp;&nbsp;4<sup>th</sup> round draft pick</span></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>Yearly Prizes:</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">1st Place = 350 $</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">2nd Place = 175 $</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">3rd Place = 75 $</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Starting Lineup:&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>10 Roster Spots</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<ul style="list-style-type: disc;margin-left:25.450000000000003px;">
    <li><span lang="EN-US">1 QB</span></li>
    <li><span lang="EN-US">2 RB</span></li>
    <li><span lang="EN-US">2 WR</span></li>
    <li><span lang="EN-US">1 TE</span></li>
    <li><span lang="EN-US">1 Super Flex</span></li>
    <li><span lang="EN-US">1 Flex</span></li>
    <li><span lang="EN-US">1 K</span></li>
    <li><span lang="EN-US">1 DEF</span></li>
</ul>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Super Flex = QB, RB, WR or TE</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Flex = RB, WR or TE</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Each Starting Lineup slot will lock individually at the scheduled game time of the player in each slot.</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>Positional Limits&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">A max. of 2 DEF can be held on Roster</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>Startup Draft Positions:&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Drawn at random when league is paid in full</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Startup Draft:&nbsp;24 round serpentine (snake) online draft - Veterans &amp; Free agents only</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Online Slow Draft with a 12-hour timer per pick</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>Rookie Draft 2022:&nbsp; &nbsp;&nbsp;</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Reversed order of Startup Draft / 4 Rounds in Snake format</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Online Slow Draft with a 12-hour timer per pick</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>Rookie Draft 2023 and onwards&nbsp; &nbsp; &nbsp;&nbsp;</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Linear Drafts of 4 rounds, will include rookies only and will take place after the NFL draft</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Online Slow Draft with an 8 hours timer per pick</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>Draft Picks Assignment&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</strong></p>
<div style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;'>
    <ul style="list-style-type: disc;margin-left:25.450000000000003px;">
        <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;'>Will be assigned based on Max Points For (during Regular Season) for the 9 teams not winning any Prizes&nbsp;</li>
    </ul>
</div>
<p style="margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:36.0pt;font-size: medium;font-family: Calibri, sans-serif;margin: 0cm 0cm 0cm 35.45pt;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">(i.e. Team with lowest Max PF will get 1st Pick of each Round, Team with 2nd lowest Max PF will get 2nd Pick, etc.)</p>
<ul style="list-style-type: disc;margin-left:25.450000000000003px;">
    <li><span lang="EN-US">10th Pick of each Round will be assigned to 3rd Placed Team of previous Season</span></li>
    <li><span lang="EN-US">11th Pick of each Round will be assigned to 2nd Placed Team of previous Season</span></li>
    <li><span lang="EN-US">12th Pick of each Round will be assigned to 1st Placed Team of previous Season</span></li>
</ul>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>Format (Regular Season):&nbsp; &nbsp; &nbsp;</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Weeks 1-14</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Head 2 Head Matchups (two games each against Divisional Teams / one game each against non Divisional Teams)</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>Format (League Playoffs):&nbsp; &nbsp; &nbsp;</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Six (6) teams advance to League Playoffs.&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Three (3) Division winners&nbsp;- Seeds #1 - #3 based on best Record / Tie breaker is Points For</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Two (2) teams with the best records among the remaining teams - Seeds #4 - #5 based on best Record / Tie breaker is Points For</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">One (1) team with the highest scored points for among the remaining teams - Seed #6</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>Weeks 15-17</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Top 2 seeds get bye week in Week 15</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">During Week 15, seed #3 plays against seed #6 / seed #4 plays against seed #5. The winners move on to the next round</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">During Weeks 16, seeds #1 will play against the lowest remaining seeded team and seed #2, will play against the highest remaining from Wild Card Round&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">During Week 17, there will be the RedCom Bowl and the final for 3rd Place</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>Free Agency In Season:&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Waivers by way of blind bidding (FAAB)</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Each team gets $100 blind bidding &ldquo;dollars&rdquo; for the entire Season</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Continuous Waivers 12am EST</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">1 weekly free agency (FA) on Sunday</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">NFL players whose teams played on Thursday may be dropped from rosters on Friday as long as they were not in that team&rsquo;s Thursday&rsquo;s starting lineup</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>TIME PLAYERS ARE ON WAIVERS AFTER DROP&nbsp; &nbsp; &nbsp; &nbsp;</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">1 Day</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>GAMES WAIVERS CLEAR&nbsp; &nbsp; &nbsp; &nbsp;</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Tuesday End of Day (00:00 PST)</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>Free Agency Off Season:&nbsp; &nbsp; &nbsp; &nbsp;</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">First free agency is scheduled one day after Rookie draft is completed</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Each team gets $100 blind bidding &ldquo;dollars&rdquo; for the entire Off-season</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Continuous Waivers 12am EST for the entire Off-Season</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>TIME TO REVIEW PENDING TRADES</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">None - Trades are processed immediately</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Any sign of collusion to maximize the chance of winning will be examined throughfully and in confirmed cases will cause the removal of the involved managers from the League.</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>Trade Deadline&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">None</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>Roster Requirement</strong>:</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">24 Total roster spots during NFL season</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">4 Taxi Squad slots</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">5 Injured Reserve (IR) slots / Eligible IR player status types are SUS (suspended) / COV (covid) &amp; IR (Injured reserve)</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Players with (Q) Questionable,&nbsp;&nbsp;(D) Doubtful or (O) Out designation are not eligible for the injured reserve</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>Scoring&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Passing Yards= +0.04 per yard&nbsp;<strong>&nbsp;</strong>(25 yards = 1 point)</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Passing TD = +4</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">2-Pt Conversion = +2</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Pass Intercepted= -2</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Rushing Yards = +0.1 per yard ((10 yards = 1 point)</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Rushing TD = +6</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">2-Pt Conversion = +2</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Reception = +0.50</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Receiving Yards = +0.1 per yard&nbsp;&nbsp;(10 yards = 1 point)</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Receiving TD = +6</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">2-Pt Conversion = +2</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Points per Field Goal Yard = +0.05 (e.g. 50 yds FG = 2.5 Pts)</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">PAT Made = +0.5</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Defense TD = +6</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Points Allowed 0 = +10</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Points Allowed 1-6 = +7</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Points Allowed 7-13 = +4</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Points Allowed 14-20 = +1</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Points Allowed 28-34 = -1</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Points Allowed 35+ = -4</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Sacks = +1</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Interceptions = +2</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Fumble Recovery = +2</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Safety = +2</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Blocked Kick = +1</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Special Teams TD = +6</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Special Teams Fumble Recovery = +2</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Miscellaneous&nbsp;Fumble Lost = -2</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Fumble Recovery TD = +6</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>Tie Breaker&nbsp; &nbsp; &nbsp;</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">In case of a tie during the playoffs the following tie-breaker rules will apply:</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">1) Bench Points Total (not including Taxi and IR)</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">2) QB Points</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">3) RB Points</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">4) WR Points</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>Rule changes&nbsp;&nbsp;</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">All formal rule changes must be done during the offseason. The offseason period is considered the day after the RedCom Superbowl and the day before the rookie draft occurs.&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">To amend any rule or regulation as defined in the bylaws, or to add another rule or regulation to it, a league member must bring the suggestion to the attention of the Commissioner in writing. The Commissioner will then present all of the specifics of the rules to the league members. A vote will be held&nbsp;<span style="color: rgb(0, 176, 80);">and 75 % members of the league (9 of 12) must vote in favour&nbsp;</span><s><span style="color: red;">all members of the league must vote unanimously</span></s><span style="color: red;">&nbsp;</span>to change an existing rule or add a new rule. If a suggestion is voted down, the owner who offered the suggestion can revise the rule offering and present again. If the suggestion is voted down a second time, the matter will be closed for that season and can be reopened the following offseason.</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
    <li><span lang="EN-US">1 DEF</span></li>
</ul>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Super Flex = QB, RB, WR or TE</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Flex = RB, WR or TE</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Each Starting Lineup slot will lock individually at the scheduled game time of the player in each slot.</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>Number of teams</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">12</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>Divisions&nbsp;</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">3 (Random assignment)</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">After each season, the divisions will be recast randomly</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>Fee:&nbsp; &nbsp; &nbsp;</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">50$ per Season/Team</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Seasons 2022 and 2023 (i.e. 100 $) to be paid upfront before Startup Draft&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">League fees will be managed through Leaguesafe</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Future Draft Picks can be traded only in case that Participation fee for that season has been paid in full.</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><s><span style="color: rgb(192, 0, 0);">Late payment for 2024 will cause Rookie Picks to be removed from the involved manager (more details will follow)</span></s></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style="color: rgb(83, 129, 53);">New rule applicable from 2023-03-25 onwards:</span></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style="color: rgb(83, 129, 53);">League fees must be paid 1 year in advance. Deadline: 1 day prior to the official NFL rookie draft&nbsp;</span></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style="color: rgb(83, 129, 53);">Example 1) in order to have no penalty rookie picks removed, league fee 2025 must be paid until approx. end April 2024</span></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style="color: rgb(83, 129, 53);">Example 2) in order to have no penalty rookie picks removed, league fee 2026 must be paid until approx. end April 2025&nbsp;</span></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style="color: rgb(83, 129, 53);">and so on&hellip;</span></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style="color: rgb(83, 129, 53);">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style="color: rgb(83, 129, 53);">In case of delayed payments the following penalty will be applied</span></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style="color: rgb(83, 129, 53);">Up to 1 week delay = no 1<sup>st</sup> round draft pick in the corresponding draft year (i.e. 2025 in example 1, 2026 in example 2)</span></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style="color: rgb(83, 129, 53);">Up to 2 weeks delay = no 1<sup>st</sup> + 2<sup>nd</sup> round draft pick</span></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style="color: rgb(83, 129, 53);">Up to 3 weeks delay = no 1<sup>st</sup> + 2<sup>nd</sup> + 3<sup>rd</sup> round draft pick</span></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><span style="color: rgb(83, 129, 53);">Up to 4 weeks delay = no 1<sup>st</sup> + 2<sup>nd</sup> + 3<sup>rd&nbsp;&nbsp;</sup>+&nbsp;&nbsp;4<sup>th</sup> round draft pick</span></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>Yearly Prizes:</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">1st Place = 350 $</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">2nd Place = 175 $</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">3rd Place = 75 $</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Starting Lineup:&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>10 Roster Spots</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<ul style="list-style-type: disc;margin-left:25.450000000000003px;">
    <li><span lang="EN-US">1 QB</span></li>
    <li><span lang="EN-US">2 RB</span></li>
    <li><span lang="EN-US">2 WR</span></li>
    <li><span lang="EN-US">1 TE</span></li>
    <li><span lang="EN-US">1 Super Flex</span></li>
    <li><span lang="EN-US">1 Flex</span></li>
    <li><span lang="EN-US">1 K</span></li>
    <li><span lang="EN-US">1 DEF</span></li>
</ul>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Super Flex = QB, RB, WR or TE</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Flex = RB, WR or TE</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Each Starting Lineup slot will lock individually at the scheduled game time of the player in each slot.</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>Positional Limits&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">A max. of 2 DEF can be held on Roster</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>Startup Draft Positions:&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Drawn at random when league is paid in full</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Startup Draft:&nbsp;24 round serpentine (snake) online draft - Veterans &amp; Free agents only</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Online Slow Draft with a 12 hour timer per pick</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>Rookie Draft 2022:&nbsp; &nbsp;&nbsp;</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Reversed order of Startup Draft / 4 Rounds in Snake format</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Online Slow Draft with a 12 hour timer per pick</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>Rookie Draft 2023 and onwards&nbsp; &nbsp; &nbsp;&nbsp;</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Linear Drafts of 4 rounds, will include rookies only and will take place after the NFL draft</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Online Slow Draft with a 12 hour timer per pick</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Draft Picks Assignment&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</p>
<div style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;'>
    <ul style="list-style-type: disc;margin-left:25.450000000000003px;">
        <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;'>Will be assigned based on Max Points For (during Regular Season) for the 9 teams not winning any Prizes&nbsp;</li>
    </ul>
</div>
<p style="margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:36.0pt;font-size: medium;font-family: Calibri, sans-serif;margin: 0cm 0cm 0cm 35.45pt;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">(i.e. Team with lowest Max PF will get 1st Pick of each Round, Team with 2nd lowest Max PF will get 2nd Pick, etc.)</p>
<ul style="list-style-type: disc;margin-left:25.450000000000003px;">
    <li><span lang="EN-US">10th Pick of each Round will be assigned to 3rd Placed Team of previous Season</span></li>
    <li><span lang="EN-US">11th Pick of each Round will be assigned to 2nd Placed Team of previous Season</span></li>
    <li><span lang="EN-US">12th Pick of each Round will be assigned to 1st Placed Team of previous Season</span></li>
</ul>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>Format (Regular Season):&nbsp; &nbsp; &nbsp;</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Weeks 1-14</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Head 2 Head Matchups (two games each against Divisional Teams / one game each against non Divisional Teams)</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>Format (League Playoffs):&nbsp; &nbsp; &nbsp;</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Six (6) teams advance to League Playoffs.&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Three (3) Division winners&nbsp;- Seeds #1 - #3 based on best Record / Tie breaker is Points For</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Two (2) teams with the best records among the remaining teams - Seeds #4 - #5 based on best Record / Tie breaker is Points For</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">One (1) team with the highest scored points for among the remaining teams - Seed #6</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>Weeks 15-17</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Top 2 seeds get bye week in Week 15</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">During Week 15, seed #3 plays against seed #6 / seed #4 plays against seed #5. The winners move on to the next round</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">During Weeks 16, seeds #1 will play against the lowest remaining seeded team and seed #2, will play against the highest remaining from Wild Card Round&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">During Week 17, there will be the RedCom Bowl and the final for 3rd Place</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>Free Agency In Season:&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Waivers by way of blind bidding (FAAB)</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Each team gets $100 blind bidding &ldquo;dollars&rdquo; for the entire Season</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Continuous Waivers 12am EST</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">1 weekly free agency (FA) on Sunday</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">NFL players whose teams played on Thursday may be dropped from rosters on Friday as long as they were not in that team&rsquo;s Thursday&rsquo;s starting lineup</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>TIME PLAYERS ARE ON WAIVERS AFTER DROP&nbsp; &nbsp; &nbsp; &nbsp;</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">1 Day</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>GAMES WAIVERS CLEAR&nbsp; &nbsp; &nbsp; &nbsp;</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Tuesday End of Day (00:00 PST)</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>Free Agency Off Season:&nbsp; &nbsp; &nbsp; &nbsp;</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">First free agency is scheduled one day after Rookie draft is completed</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Each team gets $100 blind bidding &ldquo;dollars&rdquo; for the entire Off-season</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Continuous Waivers 12am EST for the entire Off-Season</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>TIME TO REVIEW PENDING TRADES</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">None - Trades are processed immediately</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Any sign of collusion to maximize the chance of winning will be examined throughfully and in confirmed cases will cause the removal of the involved managers from the League.</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>Trade Deadline&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">None</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>Roster Requirement</strong>:</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">24 Total roster spots during NFL season</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">4 Taxi Squad slots</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">5 Injured Reserve (IR) slots / Eligible IR player status types are SUS (suspended) / COV (covid) &amp; IR (Injured reserve)</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Players with (Q) Questionable,&nbsp;&nbsp;(D) Doubtful or (O) Out designation are not eligible for the injured reserve</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>Scoring&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Passing Yards= +0.04 per yard&nbsp;<strong>&nbsp;</strong>(25 yards = 1 point)</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Passing TD = +4</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">2-Pt Conversion = +2</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Pass Intercepted= -2</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Rushing Yards = +0.1 per yard ((10 yards = 1 point)</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Rushing TD = +6</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">2-Pt Conversion = +2</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Reception = +0.50</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Receiving Yards = +0.1 per yard&nbsp;&nbsp;(10 yards = 1 point)</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Receiving TD = +6</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">2-Pt Conversion = +2</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Points per Field Goal Yard = +0.05 (e.g. 50 yds FG = 2.5 Pts)</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">PAT Made = +0.5</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Defense TD = +6</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Points Allowed 0 = +10</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Points Allowed 1-6 = +7</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Points Allowed 7-13 = +4</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Points Allowed 14-20 = +1</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Points Allowed 28-34 = -1</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Points Allowed 35+ = -4</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Sacks = +1</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Interceptions = +2</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Fumble Recovery = +2</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Safety = +2</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Blocked Kick = +1&quot;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Special Teams TD = +6</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Special Teams Fumble Recovery = +2</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Miscellaneous&nbsp;Fumble Lost = -2</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">Fumble Recovery TD = +6</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>Tie Breaker&nbsp; &nbsp; &nbsp;</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">In case of a tie during the playoffs the following tie-breaker rules will apply:</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">1) Bench Points Total (not including Taxi and IR)</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">2) QB Points</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">3) RB Points</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">4) WR Points&quot;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;"><strong>Rule changes&nbsp;&nbsp;</strong></p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">All formal rule changes must be done during the offseason. The offseason period is considered the day after the RedCom Superbowl and the day before the rookie draft occurs.&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">To amend any rule or regulation as defined in the bylaws, or to add another rule or regulation to it, a league member must bring the suggestion to the attention of the Commissioner in writing. The Commissioner will then present all of the specifics of the rules to the league members. A vote will be held&nbsp;<span style="color: rgb(0, 176, 80);">and 75 % members of the league (9 of 12) must vote in favour&nbsp;</span><s><span style="color: red;">all members of the league must vote unanimously</span></s><span style="color: red;">&nbsp;</span>to change an existing rule or add a new rule. If a suggestion is voted down, the owner who offered the suggestion can revise the rule offering and present again. If the suggestion is voted down a second time, the matter will be closed for that season and can be reopened the following offseason.</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
<p style="margin: 0cm 0cm 0cm 35.45pt;font-size: medium;font-family: Calibri, sans-serif;color: rgb(0, 0, 0);font-style: normal;font-weight: 400;text-align: start;text-indent: 0px;text-decoration: none;">&nbsp;</p>
